const ServicesActionTypes = {
	FETCH_SERVICES_SUCCESS: 'services/FETCH_SERVICES_SUCCESS',
	FETCH_SERVICES_FAILED: 'services/FETCH_SERVICES_FAILED',
	FILTER_SERVICES_BY_CATEGORY: 'services/FILTER_SERVICES_BY_CATEGORY',
	SEARCH_SERVICES_BY_CATEGORY: 'services/SEARCH_SERVICES_BY_CATEGORY'
}

export default ServicesActionTypes;