const OrdersActionTypes = {
	ADD_NEW_ORDER_SUCCESS: 'order/ADD_NEW_ORDER_SUCCESS',
	ADD_NEW_ORDER_PENDING: 'order/ADD_NEW_ORDER_PENDING',
	ADD_NEW_ORDER_FAILED: 'order/ADD_NEW_ORDER_FAILED',
	FETCH_ALL_ORDERS_SUCCESS: 'order/FETCH_ALL_ORDERS_SUCCESS',
	FETCH_ALL_ORDERS_PENDING: 'order/FETCH_ALL_ORDERS_PENDING',
	FILTER_ORDERS_BY_STATUS: 'order/FILTER_ORDERS_BY_STATUS'
};

export default OrdersActionTypes;